pa4: main.o inorder.o add.o search.o find_largest.o delete.o largest_parent.o postorder.o preorder.o height.o print_level.o free_level.o
	gcc -o pa4 main.o inorder.o add.o search.o find_largest.o delete.o largest_parent.o postorder.o preorder.o height.o print_level.o free_level.o

main.o: main.c mylib.h
	gcc -c main.c

inorder.o: inorder.c mylib.h
	gcc -c inorder.c

add.o: add.c mylib.h
	gcc -c add.c

search.o: search.c mylib.h
	gcc -c search.c

delete.o: delete.c mylib.h
	gcc -c delete.c

find_largest.o: find_largest.c mylib.h
	gcc -c find_largest.c

largest_parent.o: largest_parent.c mylib.h
	gcc -c largest_parent.c

postorder.o: postorder.c mylib.h
	gcc -c postorder.c

preorder.o: preorder.c mylib.h
	gcc -c preorder.c

height.o: height.c mylib.h
	gcc -c height.c

print_level.o: print_level.c mylib.h
	gcc -c print_level.c

free_level.o: free_level.c mylib.h
	gcc -c free_level.c
